//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_PIM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class CadEmpresa
    {
        public int ID { get; set; }
        public string RazaoSocial { get; set; }
        public string Email { get; set; }
        [Required(ErrorMessage = "A senha é obrigatória.")]
        [StringLength(100, MinimumLength = 6, ErrorMessage = "A senha deve ter entre 6 e 100 caracteres.")]
        public string Senha { get; set; }
        [Required(ErrorMessage = "O CNPJ é obrigatório.")]
        public string CNPJ { get; set; }
        public string Telefone { get; set; }
        public string CEP1 { get; set; }
        public Nullable<int> Numero1 { get; set; }
        public string Complemento1 { get; set; }
        public string Rua1 { get; set; }
    }
}
